version = 0.1
[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "spirits-dev-businessops-api"
s3_bucket = "spirits-dev-samdeploy"
s3_prefix = "spirits-dev-businessops-api"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "Application=\"spirits\" Module=\"businessops\" Environment=\"dev\" QueryLimit=\"20\" LogLevel=\"INFO\" RetentionInDays=\"30\" EventBusName=\"/spirits/dev/platform/eventbus/arn\" NodeLayerArn=\"/spirits/dev/shared/nodelayer/arn\" ElasticSearchDomainEndpoint=\"/spirits/dev/elasticsearch/domain/endpoint\" BusinessopspoolId=\"/spirits/dev/platform/businessopsuserpool/id\" "


[sit]
[sit.deploy]
[sit.deploy.parameters]
stack_name = "spirits-sit-businessops-api"
s3_bucket = "spirits-dev-samdeploy"
s3_prefix = "spirits-sit-businessops-api"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "Application=\"spirits\" Module=\"businessops\" Environment=\"sit\" QueryLimit=\"20\" LogLevel=\"INFO\" RetentionInDays=\"30\" EventBusName=\"/spirits/sit/platform/eventbus/arn\" NodeLayerArn=\"/spirits/sit/shared/nodelayer/arn\" ElasticSearchDomainEndpoint=\"/spirits/sit/elasticsearch/domain/endpoint\" BusinessopspoolId=\"/spirits/sit/platform/businessopsuserpool/id\" "

