version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      # Install packages or any pre-reqs in this phase.
      # Upgrading SAM CLI to latest version
      - pip3 install --upgrade aws-sam-cli
      - sam --version
      # Installing project dependencies
      - cd backend/api
      - npm install
      - cd ../..

  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - aws s3 cp s3://${ExportsBucket}/promotion-web-ui/${Environment}/aws-exports.js ./frontend/src
      - cd frontend && yarn install
      - cd ..
      # Run tests, lint scripts or any other pre-build checks.
      #- npm run test

  build:
    commands:
      # Use Build phase to build your artifacts (compile, etc.)
      - cd backend
      - cd model/business-contacts && sam build
      - cd ../../api && sam build
      - cd datasources
      - cd BusinessContact && sam build -t BusinessContact.yaml

      - cd ../..
      - cd ../..
      - echo Build started on `date`
      - cd frontend && yarn build
      - cd ..

  post_build:
    commands:
      - cd backend
      - cd model/business-contacts && sam deploy --config-env ${env} --no-confirm-changeset --no-fail-on-empty-changeset
      - cd ../../api && sam deploy --config-env ${env} --no-confirm-changeset --no-fail-on-empty-changeset
      - cd datasources/BusinessContact
      - cd ../BusinessContact && sam deploy -t BusinessContact.yaml --config-env ${env} --no-confirm-changeset --no-fail-on-empty-changeset

      - cd ../../..
      - cd frontend

      # copy the contents of /build to S3
      - aws s3 rm --recursive "s3://${DeployBucket}/"
      - aws s3 cp --recursive --acl public-read ./build s3://${DeployBucket}/
      # browser caching
      - aws s3 cp --acl public-read --cache-control="max-age=0, no-cache, no-store, must-revalidate" ./build/service-worker.js s3://${DeployBucket}/
      # set the cache-control headers for index.html to prevent browser caching
      - aws s3 cp --acl public-read --cache-control="max-age=0, no-cache, no-store, must-revalidate" ./build/index.html s3://${DeployBucket}/
      # Use Post-Build for notifications, git tags, upload artifacts to S3
      - cd ..

artifacts:
  files:
    - "**/*"
  base-directory: frontend/build
