/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
const awsmobile = {
  aws_project_region: 'us-east-1',
  aws_cognito_identity_pool_id:
  'us-east-1:baa0470a-3fb1-4104-b123-fda42bf374ea',
  // aws_cognito_identity_pool_id:
  // 'us-east-1:943e1ac4-d9e1-4cca-8209-438cc27094fb',
  aws_cognito_region: 'us-east-1',
  aws_user_pools_id: 'us-east-1_xJwkf8f3r',
  aws_user_pools_web_client_id: 'k86ri8155k3o9p3o1iir94gdh',
  oauth: {},
  aws_appsync_graphqlEndpoint:
    'https://3prifnup4vgrvctpneati65d34.appsync-api.us-east-1.amazonaws.com/graphql',
  aws_appsync_region: 'us-east-1',
  aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
};
export default awsmobile;
